=== streetsidesoftware/cspell/cspell.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "definitions": {
    "DictionaryDefinition": {
      "anyOf": [
        {
          "$ref": "#/definitions/DictionaryDefinitionPreferred"
        },
        {
          "$ref": "#/definitions/DictionaryDefinitionAlternate"
        }
      ]
    },
    "DictionaryDefinitionAlternate": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "description": "Optional description",
          "type": "string"
        },
        "file": {
          "$ref": "#/definitions/FsPath",
          "description": "Path to the file"
        },
        "name": {
          "$ref": "#/definitions/DictionaryId",
          "description": "The reference name of the dictionary, used with program language settings"
        },
        "repMap": {
          "$ref": "#/definitions/ReplaceMap",
          "description": "Replacement pairs"
        },
        "useCompounds": {
          "description": "Use Compounds",
          "type": "boolean"
        }
      },
      "required": [
        "file",
        "name"
      ],
      "type": "object"
    },
    "DictionaryDefinitionPreferred": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "description": "Optional description",
          "type": "string"
        },
        "name": {
          "$ref": "#/definitions/DictionaryId",
          "description": "The reference name of the dictionary, used with program language settings"
        },
        "path": {
          "$ref": "#/definitions/FsPath",
          "description": "Path to the file"
        },
        "repMap": {
          "$ref": "#/definitions/ReplaceMap",
          "description": "Replacement pairs"
        },
        "useCompounds": {
          "description": "Use Compounds",
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "path"
      ],
      "type": "object"
    },
    "DictionaryId": {
      "description": "This matches the name in a dictionary definition",
      "type": "string"
    },
    "FsPath": {
      "description": "A File System Path",
      "type": "string"
    },
    "Glob": {
      "description": "These are glob expressions",
      "type": "string"
    },
    "LanguageId": {
      "description": "This can be '*', 'typescript', 'cpp', 'json', etc.",
      "type": "string"
    },
    "LanguageSetting": {
      "additionalProperties": false,
      "properties": {
        "allowCompoundWords": {
          "default": false,
          "description": "True to enable compound word checking.",
          "type": "boolean"
        },
        "caseSensitive": {
          "default": false,
          "description": "Words must match case rules.",
          "type": "boolean"
        },
        "description": {
          "description": "Optional description of configuration",
          "type": "string"
        },
        "dictionaries": {
          "description": "Optional list of dictionaries to use.",
          "items": {
            "$ref": "#/definitions/DictionaryId"
          },
          "type": "array"
        },
        "dictionaryDefinitions": {
          "description": "Define additional available dictionaries",
          "items": {
            "$ref": "#/definitions/DictionaryDefinition"
          },
          "type": "array"
        },
        "enabled": {
          "default": true,
          "description": "Is the spell checker enabled",
          "type": "boolean"
        },
        "flagWords": {
          "description": "list of words to always be considered incorrect.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "id": {
          "description": "Optional identifier",
          "type": "string"
        },
        "ignoreRegExpList": {
          "$ref": "#/definitions/RegExpList",
          "description": "List of RegExp patterns or Pattern names to exclude from spell checking.\n\nExample: [\"href\"] - to exclude html href"
        },
        "includeRegExpList": {
          "$ref": "#/definitions/RegExpList",
          "description": "List of RegExp patterns or defined Pattern names to define the text to be included for spell checking. If includeRegExpList is defined, ONLY, text matching the included patterns will be checked."
        },
        "languageId": {
          "anyOf": [
            {
              "$ref": "#/definitions/LanguageId"
            },
            {
              "items": {
                "$ref": "#/definitions/LanguageId"
              },
              "type": "array"
            }
          ],
          "description": "The language id.  Ex: \"typescript\", \"html\", or \"php\".  \"*\" -- will match all languages"
        },
        "local": {
          "anyOf": [
            {
              "$ref": "#/definitions/LocaleId"
            },
            {
              "items": {
                "$ref": "#/definitions/LocaleId"
              },
              "type": "array"
            }
          ],
          "description": "The locale filter, matches against the language. This can be a comma separated list. \"*\" will match all locales."
        },
        "name": {
          "description": "Optional name of configuration",
          "type": "string"
        },
        "patterns": {
          "description": "Defines a list of patterns that can be used in ignoreRegExpList and includeRegExpList",
          "items": {
            "$ref": "#/definitions/RegExpPatternDefinition"
          },
          "type": "array"
        },
        "words": {
          "description": "list of words to be always considered correct",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "required": [
        "languageId"
      ],
      "type": "object"
    },
    "LocaleId": {
      "description": "This is a written language locale like: 'en', 'en-GB', 'fr', 'es', 'de', etc.",
      "type": "string"
    },
    "OverrideSettings": {
      "additionalProperties": false,
      "properties": {
        "allowCompoundWords": {
          "default": false,
          "description": "True to enable compound word checking.",
          "type": "boolean"
        },
        "caseSensitive": {
          "default": false,
          "description": "Words must match case rules.",
          "type": "boolean"
        },
        "description": {
          "description": "Optional description of configuration",
          "type": "string"
        },
        "dictionaries": {
          "description": "Optional list of dictionaries to use.",
          "items": {
            "$ref": "#/definitions/DictionaryId"
          },
          "type": "array"
        },
        "dictionaryDefinitions": {
          "description": "Define additional available dictionaries",
          "items": {
            "$ref": "#/definitions/DictionaryDefinition"
          },
          "type": "array"
        },
        "enabled": {
          "default": true,
          "description": "Is the spell checker enabled",
          "type": "boolean"
        },
        "enabledLanguageIds": {
          "description": "languageIds for the files to spell check.",
          "items": {
            "$ref": "#/definitions/LanguageId"
          },
          "type": "array"
        },
        "filename": {
          "anyOf": [
            {
              "$ref": "#/definitions/Glob"
            },
            {
              "items": {
                "$ref": "#/definitions/Glob"
              },
              "type": "array"
            }
          ],
          "description": "Glob pattern or patterns to match against"
        },
        "flagWords": {
          "description": "list of words to always be considered incorrect.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "id": {
          "description": "Optional identifier",
          "type": "string"
        },
        "ignorePaths": {
          "description": "Glob file patterns to be ignored",
          "items": {
            "$ref": "#/definitions/Glob"
          },
          "type": "array"
        },
        "ignoreRegExpList": {
          "$ref": "#/definitions/RegExpList",
          "description": "List of RegExp patterns or Pattern names to exclude from spell checking.\n\nExample: [\"href\"] - to exclude html href"
        },
        "ignoreWords": {
          "description": "list of words to be ignored",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "includeRegExpList": {
          "$ref": "#/definitions/RegExpList",
          "description": "List of RegExp patterns or defined Pattern names to define the text to be included for spell checking. If includeRegExpList is defined, ONLY, text matching the included patterns will be checked."
        },
        "language": {
          "$ref": "#/definitions/LocaleId",
          "description": "Sets the locale"
        },
        "languageId": {
          "$ref": "#/definitions/LanguageId",
          "description": "Sets the programming language id"
        },
        "languageSettings": {
          "description": "Additional settings for individual languages.",
          "items": {
            "$ref": "#/definitions/LanguageSetting"
          },
          "type": "array"
        },
        "maxDuplicateProblems": {
          "default": 5,
          "description": "The maximum number of times the same word can be flagged as an error in a file.",
          "type": "number"
        },
        "maxNumberOfProblems": {
          "default": 100,
          "description": "The maximum number of problems to report in a file.",
          "type": "number"
        },
        "minWordLength": {
          "default": 4,
          "description": "The minimum length of a word before checking it against a dictionary.",
          "type": "number"
        },
        "name": {
          "description": "Optional name of configuration",
          "type": "string"
        },
        "numSuggestions": {
          "default": 10,
          "description": "Number of suggestions to make",
          "type": "number"
        },
        "patterns": {
          "description": "Defines a list of patterns that can be used in ignoreRegExpList and includeRegExpList",
          "items": {
            "$ref": "#/definitions/RegExpPatternDefinition"
          },
          "type": "array"
        },
        "words": {
          "description": "list of words to be always considered correct",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "required": [
        "filename"
      ],
      "type": "object"
    },
    "Pattern": {
      "type": "string"
    },
    "PatternId": {
      "description": "This matches the name in a pattern definition",
      "type": "string"
    },
    "PatternRef": {
      "anyOf": [
        {
          "$ref": "#/definitions/Pattern"
        },
        {
          "$ref": "#/definitions/PatternId"
        },
        {
          "$ref": "#/definitions/PreDefinedPatterns"
        }
      ],
      "description": "A PatternRef is a Pattern or PatternId."
    },
    "PreDefinedPatterns": {
      "enum": [
        "Base64",
        "CStyleComment",
        "Email",
        "EscapeCharacters",
        "HexDigits",
        "HexValues",
        "href",
        "PhpHereDoc",
        "PublicKey",
        "RsaCert",
        "SHA",
        "SpellCheckerDisable",
        "string",
        "Urls",
        "Everything"
      ],
      "type": "string"
    },
    "RegExpList": {
      "items": {
        "$ref": "#/definitions/PatternRef"
      },
      "type": "array"
    },
    "RegExpPatternDefinition": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "description": "Description of the pattern.",
          "type": "string"
        },
        "name": {
          "$ref": "#/definitions/PatternId",
          "description": "Pattern name, used as an identifier in ignoreRegExpList and includeRegExpList. It is possible to redefine one of the predefined patterns to override its value."
        },
        "pattern": {
          "$ref": "#/definitions/Pattern",
          "description": "RegExp pattern"
        }
      },
      "required": [
        "name",
        "pattern"
      ],
      "type": "object"
    },
    "ReplaceEntry": {
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ],
      "maxItems": 2,
      "minItems": 2,
      "type": "array"
    },
    "ReplaceMap": {
      "items": {
        "$ref": "#/definitions/ReplaceEntry"
      },
      "type": "array"
    }
  },
  "properties": {
    "$schema": {
      "type": "string"
    },
    "allowCompoundWords": {
      "default": false,
      "description": "True to enable compound word checking.",
      "type": "boolean"
    },
    "caseSensitive": {
      "default": false,
      "description": "Words must match case rules.",
      "type": "boolean"
    },
    "description": {
      "description": "Optional description of configuration",
      "type": "string"
    },
    "dictionaries": {
      "description": "Optional list of dictionaries to use.",
      "items": {
        "$ref": "#/definitions/DictionaryId"
      },
      "type": "array"
    },
    "dictionaryDefinitions": {
      "description": "Define additional available dictionaries",
      "items": {
        "$ref": "#/definitions/DictionaryDefinition"
      },
      "type": "array"
    },
    "enabled": {
      "default": true,
      "description": "Is the spell checker enabled",
      "type": "boolean"
    },
    "enabledLanguageIds": {
      "description": "languageIds for the files to spell check.",
      "items": {
        "$ref": "#/definitions/LanguageId"
      },
      "type": "array"
    },
    "flagWords": {
      "description": "list of words to always be considered incorrect.",
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "id": {
      "description": "Optional identifier",
      "type": "string"
    },
    "ignorePaths": {
      "description": "Glob file patterns to be ignored",
      "items": {
        "$ref": "#/definitions/Glob"
      },
      "type": "array"
    },
    "ignoreRegExpList": {
      "$ref": "#/definitions/RegExpList",
      "description": "List of RegExp patterns or Pattern names to exclude from spell checking.\n\nExample: [\"href\"] - to exclude html href"
    },
    "ignoreWords": {
      "description": "list of words to be ignored",
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "import": {
      "anyOf": [
        {
          "$ref": "#/definitions/FsPath"
        },
        {
          "items": {
            "$ref": "#/definitions/FsPath"
          },
          "type": "array"
        }
      ],
      "description": "Other settings files to be included"
    },
    "includeRegExpList": {
      "$ref": "#/definitions/RegExpList",
      "description": "List of RegExp patterns or defined Pattern names to define the text to be included for spell checking. If includeRegExpList is defined, ONLY, text matching the included patterns will be checked."
    },
    "language": {
      "$ref": "#/definitions/LocaleId",
      "default": "en",
      "description": "Current active spelling language.\n\nExample: \"en-GB\" for British English\n\nExample: \"en,nl\" to enable both English and Dutch"
    },
    "languageId": {
      "$ref": "#/definitions/LanguageId",
      "description": "Forces the spell checker to assume a give language id. Used mainly as an Override."
    },
    "languageSettings": {
      "description": "Additional settings for individual languages.",
      "items": {
        "$ref": "#/definitions/LanguageSetting"
      },
      "type": "array"
    },
    "maxDuplicateProblems": {
      "default": 5,
      "description": "The maximum number of times the same word can be flagged as an error in a file.",
      "type": "number"
    },
    "maxNumberOfProblems": {
      "default": 100,
      "description": "The maximum number of problems to report in a file.",
      "type": "number"
    },
    "minWordLength": {
      "default": 4,
      "description": "The minimum length of a word before checking it against a dictionary.",
      "type": "number"
    },
    "name": {
      "description": "Optional name of configuration",
      "type": "string"
    },
    "numSuggestions": {
      "default": 10,
      "description": "Number of suggestions to make",
      "type": "number"
    },
    "overrides": {
      "description": "Overrides to apply based upon the file path.",
      "items": {
        "$ref": "#/definitions/OverrideSettings"
      },
      "type": "array"
    },
    "patterns": {
      "description": "Defines a list of patterns that can be used in ignoreRegExpList and includeRegExpList",
      "items": {
        "$ref": "#/definitions/RegExpPatternDefinition"
      },
      "type": "array"
    },
    "showStatus": {
      "description": "Show status",
      "type": "boolean"
    },
    "spellCheckDelayMs": {
      "description": "Delay in ms after a document has changed before checking it for spelling errors.",
      "type": "number"
    },
    "userWords": {
      "description": "Words to add to dictionary -- should only be in the user config file.",
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "version": {
      "default": "0.1",
      "description": "Configuration format version of the setting file.",
      "type": "string"
    },
    "words": {
      "description": "list of words to be always considered correct",
      "items": {
        "type": "string"
      },
      "type": "array"
    }
  },
  "type": "object"
}

=== streetsidesoftware/cspell/packages/cspell-lib/cSpell.json
{
    "version": "0.1",
    "id": "cspell-project-config",
    "name": "cspell Project Config",
    "language": "en",
    "words": [
        "configstore",
        "gensequence",
        "WORDCHARS",
        "xregexp"
    ],
    "maxNumberOfProblems": 100,
    "ignorePaths": [
        "dictionaries/**",
        "migrated_dictionaries/**",
        "node_modules/**",
        "coverage/**",
        ".git/**",
        "dist/**",
        "package.json",
        "**/package.json",
        "**/.cspell.json",
        ".vscode/**"
    ],
    "allowCompoundWords": false,
    "dictionaryDefinitions": [],
    "ignoreWords": [
        "istanbuljs"
    ]
}

=== streetsidesoftware/cspell/test-fixtures/issues/issue-5034/.cspell.json
{
    "version": "0.2",
    "ignorePaths": [
        ".neoconf.json",
        ".vscode/settings.json",
        ".vim/coc-settings.json",
        "frontend/node_modules/**",
        "frontend/coverage/**",
        "frontend/build/**",
        "frontend/db/dist/**",
        "frontend/package.json",
        "frontend/public/locales/ar/**",
        "frontend/public/locales/zgh/**",
        "frontend/public/supportedBrowsers.js",
        "docker-compose*.yml",
        "cloudformation.yml",
        "vendor",
        "web/src/composer.json",
        "web/src/vendor",
        "web/src/shared/scripts",
        "web/src/css",
        "web/src/locales/ar/translations.yml",
        "node/src/locales/ar.json",
        "web/src/locales/zgh/translations.yml",
        "web/src/api/Validation/lang/ar/validation.php",
        ".env",
        "renovate.json",
        "web/conf/**/*",
        "*Dockerfile"
    ],
    "allowCompoundWords": true,
    "ignoreWords": [
        "culturehq",
        "yiisoft",
        "lintstagedrc",
        "rehype",
        "noto",
        "graphiql",
        "webp"
    ],
    "words": [
        "AMZN",
        "capce",
        "cedata",
        "crunz",
        "cronitor",
        "destructured",
        "droppable",
        "entityid",
        "esetnik",
        "esnext",
        "falsey",
        "Gravatar",
        "hacky",
        "Handtevy",
        "hocs",
        "iframe",
        "imgix",
        "immer",
        "junit",
        "jwplayer",
        "JWPLAYER",
        "Lngs",
        "luxon",
        "Maknz",
        "Mebibytes",
        "msodbcsql",
        "newid",
        "noopener",
        "NREMT",
        "nuka",
        "oems",
        "onstatechange",
        "onupdatefound",
        "phpcs",
        "phpcbf",
        "phuocng",
        "recertification",
        "reduxjs",
        "resizer",
        "signup",
        "testid",
        "tamazight",
        "tifinagh",
        "tsql",
        "Tuupola",
        "unmount",
        "unregister",
        "UPDLOCK",
        "wdyr",
        "xlarge"
    ],
    "import": [
        "./frontend/node_modules/@cspell/dict-fr-fr/cspell-ext.json"
    ],
    "overrides": [
        {
            "filename": "**/*.md",
            "language": "en,fr"
        },
        {
            "filename": "**/locales/fr/**/{*.json,*.yml}",
            "language": "en,fr"
        },
        {
            "filename": "**/__test__/**",
            "language": "en,fr"
        },
        {
            "filename": "**/{*.test.ts,*.test.tsx}",
            "language": "en,fr"
        },
        {
            "filename": "**/Validation/lang/fr/validation.php",
            "language": "en,fr"
        },
        {
            "filename": "node/src/locales/fr.json",
            "language": "en,fr"
        },
        {
            "filename": "frontend/src/themes/*.json",
            "languageId": "css"
        }
    ]
}
